/********************************
* Microsoft Object Record Types *
********************************/
#define BLKDEF  0x7A
#define BLKEND  0x7C
#define THEADR  0x80
#define COMENT  0x88
#define MODEND  0x8A
#define EXTDEF  0x8C
#define TYPDEF  0x8E
#define PUBDEF  0x90
#define LINNUM  0x94
#define LNAMES  0x96
#define SEGDEF  0x98
#define GRPDEF  0x9A
#define FIXUPP  0x9C
#define LEDATA  0xA0
#define LIDATA  0xA2
#define COMDEF  0xB0    /* communal-names definition */

/********************************
* Intel Object Record Types     *
********************************/
#define RHEADR  0x6E
#define REGINT  0x70
#define REDATA  0x72
#define RIDATA  0x74
#define OVLDEF  0x76
#define ENDREC  0x78
#define DEBSYM  0x7E
#define LHEADR  0x82
#define PEDATA  0x84
#define PIDATA  0x86
#define LOCSYM  0x92
#define LIBHED  0xA4
#define LIBNAM  0xA6
#define LIBLOC  0xA8
#define LIBDIC  0xAA

/* Defininiciones Libreria */

#define LIBHDR  0xf0
#define LIBTRL  0xf1



