// printer driver definition

#define DC_NAME             1
#define DC_RIGHT            2
#define DC_INIT             3
#define DC_NORMAL           4
#define DC_EXPANDED         5
#define DC_COMPRESSED       6
#define DC_UNDERLINE        7
#define DC_UNDERLINE_OFF    8
#define DC_BOLD             9
#define DC_BOLD_OFF        10
#define DC_ITALIC          11
#define DC_ITALIC_OFF      12
#define DC_OVER            13
#define DC_OVER_OFF        14
