
// Styles

#define WND_LCLOSE         1
#define WND_LFLOAT         2
#define WND_LGROW          4
#define WND_LHSCROLL       8       // WS_HSCROLL
#define WND_LICONIZE      16       // WS_MINIMIZEBOX
#define WND_LMAXIMIZED    32       // WS_MAXIMIZE
#define WND_LMODAL        64
#define WND_LMINIMIZED   128       // WS_MINIMIZE
#define WND_LSHADOW      256
#define WND_LVSCROLL     512       // WS_VSCROLL
#define WND_LZOOM       1024       // WS_MAXIMIZEBOX

