static aSysClr := {  48 ,;     //    "N/BG   "     // Window
                    240 ,;     //    "N/W*   "
                     63 ,;     //    "W+/BG  "
                    112 ,;     //    "N/W    "
                     55 ,;     //    "W/BG   "
                      0 ,;     // SPARE
                      0 ,;     // SPARE
                     48 ,;     //    "N/BG   "     // Label
                     63 ,;     //    "W+/BG  "
                     59 ,;     //    "BG+/BG "
                     59 ,;     //    "BG+/BG "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // PushButton
                    127 ,;     //    "W+/W   "
                    123 ,;     //    "BG+/W  "
                    123 ,;     //    "BG+/W  "
                      0 ,;     // SPARE
                    128 ,;     //    "N/N*   "     // ButtonBar
                    143 ,;     //    "W+/N*  "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // ButtonBmp
                    127 ,;     //    "W+/W   "
                    112 ,;     //    "N/W    "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // CheckBox
                    127 ,;     //    "W+/W   "
                    123 ,;     //    "BG+/W  "
                    120 ,;     //    "N+/W   "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // TGet
                    127 ,;     //    "W+/W   "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // TCombo
                    127 ,;     //    "W+/W   "
                     15 ,;     //    "W+/N   "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // TListBox
                     31 ,;     //    "W+/B   "
                    127 ,;     //    "W+/W   "
                      0 ,;     // SPARE
                     31 ,;     //    "W+/B   "     // Menus y menuitems
                    113 ,;     //    "B/W    "
                     28 ,;     //    "R+/B   "
                    124 ,;     //    "R+/W   "
                     23 ,;     //    "W/B    "
                     25 ,;     //    "B+/B   "
                     24 ,;     //    "N+/B   "
                      0 ,;     // SPARE
                     48 ,;     //    "N/BG   "     // RadioButton
                     63 ,;     //    "W+/BG  "
                     59 ,;     //    "BG+/BG "
                     56 ,;     //    "N+/BG  "
                      0 ,;     // SPARE
                    112 ,;     //    "N/W    "     // RadioMenus
                    127 ,;     //    "W+/W   "
                    123 ,;     //    "BG+/W  "
                    120 ,;     //    "N+/W   "
                      0 ,;     // SPARE
                    135 ,;     //    "W/N*   "     // ScrollBar
                    112 ,;     //    "N/W    "
                    127 ,;     //    "W+/W   "
                      0 ,;     // SPARE
       "n/w, w+/b, w/b" ,;
                      0 ,;     // SPARE
                    135 ,;     //    "W/N*   "     // Tabs
                     96 ,;     //    "N/GR   "
                    142 ,;     //    "GR+/N* "
                    110 ,;     //    "GR+/GR "
                     56 ,;     //    "N+/BG  "
                     54 ,;     //    "GR/BG  "
                      0  ;     // SPARE

