//----------------------------------------------------------------------------//
//  FiveDos - Tutorial
//  (c) FiveDos Team 1994
//
//  Para construir:  BUILD Tutor01
//  To build:        BUILD Tutor01
//----------------------------------------------------------------------------//

#include "FiveDos.ch"

//----------------------------------------------------------------------------//

function Main()

    MsgInfo( F2VERSION + CRLF + CRLF + FDCOPYRIGHT ,;
             "Clipper for MS-Dos Library" )

return nil

//----------------------------------------------------------------------------//
